# fly.toml app configuration file generated for mint-scraper on 2023-08-27T09:25:45-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mint-scraper"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PRIMARY_REGION = "sea"
  SESSION_FILE_PATH = "/data/.sessions.pkl"
  
[processes]
  scraper = "/app/serve.sh"


[mounts]
  source = "mint_session_data"
  destination = "data"